openapi: 3.0.1
info:
  title: Credentials APIs
  description: API for Credentials
  version: 1.1.0
tags:
- name: Credentials
  description: Operations related to Credentials Management
paths:
  /api/v1/accounts/{account-id}/credentials:
    get:
      tags:
      - Credentials
      summary: Get Credentials list for an account
      operationId: getCredentials
      parameters:
      - name: integration
        in: query
        description: integration Name
        required: false
        style: form
        explode: true
        allowReserved: true
        schema:
          type: array
          items:
            $ref: "../schema/schemas.yaml#/components/schemas/IntegrationId"
      - name: vendor
        in: query
        description: vendor name
        required: false
        style: form
        explode: true
        allowReserved: true
        schema:
          type: string
      - name: page
        in: query
        description: Pagination field
        required: false
        style: form
        explode: true
        schema:
          type: integer
          default: 1
      - name: limit
        in: query
        description: Pagination limit
        required: false
        style: form
        explode: true
        schema:
          type: integer
          default: 20
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Credentials List
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/GetCredentialListResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Credentials not found
                statusCode: "404"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Internal server error
                statusCode: "500"
    post:
      tags:
      - Credentials
      summary: Create Credential for an account
      operationId: createCredential
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Credential details
        content:
          application/json:
            schema:
              $ref: "../schema/schemas.yaml#/components/schemas/CreateCredentialRequest"
        required: true
      responses:
        "200":
          description: Credential creation success response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/CredentialCommonResponse"
              example:
                status: SUCCESS
                message: Credential Created Successfully
                credentialId: 1
        "400":
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Invalid request parameters
                statusCode: "400"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Internal server error
                statusCode: "500"
  /api/v1/accounts/{account-id}/credentials/{credential-id}/key-location:
    get:
      tags:
      - Credentials
      summary: Get the key location (ARN) of the given credential
      operationId: getKeyLocationByCredentialId
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: credential-id
        in: path
        description: The Credential Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: keyType
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - DataKey
          - RootKey
      responses:
        "200":
          description: Key Location retrieved successfully
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/KeyLocationResponse"
              example:
                arn: arn:aws:kms:us-west-2:123456789012:key/abcd1234-efgh-5678-ijkl-9876543210mn
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Invalid request parameters
                statusCode: "400"
        "404":
          description: Key location for the credential is not found
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: key location is not found
                statusCode: "404"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Internal server error
                statusCode: "500"
  /api/v1/accounts/{account-id}/credentials/oauth/_init:
    get:
      tags:
      - Credentials
      summary: Initiate oauth integration
      operationId: initIntegrate
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: provider
        in: query
        description: The oauth provider name
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: state
        in: query
        description: The state value from requester
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: URL for redirection
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Error on initiating oauth integration
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
        "500":
          description: Error on initiating oauth integration
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
  /api/v1/accounts/{account-id}/credentials/{credential-id}:
    get:
      tags:
      - Credentials
      summary: Get the Credential record by Id
      operationId: getCredentialById
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: credential-id
        in: path
        description: The Id of the Credential
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Credential Record for given Id
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/GetCredentialResponse"
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Invalid account ID or credential ID
                statusCode: "404"
        "404":
          description: Credential not found
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Credential not found
                statusCode: "404"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Internal server error
                statusCode: "500"
    put:
      tags:
      - Credentials
      summary: Update Credential record by Credential Id
      operationId: updateCredentialById
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: credential-id
        in: path
        description: The Credential Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Update Credential details
        content:
          application/json:
            schema:
              $ref: "../schema/schemas.yaml#/components/schemas/UpdateCredentialRequest"
        required: true
      responses:
        "200":
          description: Credential update success response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/CredentialCommonResponse"
              example:
                status: SUCCESS
                message: Credential Updated Successfully
                credentialId: 1
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Invalid request parameters
                statusCode: "400"
        "404":
          description: Credential not found
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Credential not found
                statusCode: "404"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Internal server error
                statusCode: "500"
    delete:
      tags:
      - Credentials
      summary: Delete credential record by credential Id
      operationId: deleteCredentialById
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: credential-id
        in: path
        description: The Credential Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful credential deletion response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/CredentialCommonResponse"
              example:
                status: SUCCESS
                message: Credential Deleted Successfully
                credentialId: 1
        "400":
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: The Credential requested to delete is being in use by connectors
                statusCode: "400"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Credential not found
                statusCode: "404"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
              example:
                status: ERROR
                message: Internal server error
                statusCode: "500"
  /api/v1/accounts/{account-id}/credentials/oauth/_generate:
    post:
      tags:
      - Credentials
      summary: Generate oauth tokens
      operationId: generateOAuthAuthorizeToken
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "../schema/schemas.yaml#/components/schemas/CreateOAuthAuthorizeCredentialRequest"
        required: true
      responses:
        "200":
          description: Credential creation success response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/CredentialCommonResponse"
        "400":
          description: Error on oauth token generation
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
        "500":
          description: Error on oauth token generation
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/ErrorResponse"
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
